### PR TITLE
1.2 from robinZhao

### PR DESCRIPTION
**Pull request by robinZhao**

### CODE REVIEW

**Comment by paulvi** [comment]
Hi Robin

Can you take over the project?

**Comment by robinZhao** [comment]
I don't have much time to take over,just make some changes  for my own situation..thank you..

**Comment by paulvi** [comment]
Why do you hurry to close?
Is it tested? Does it work?

When I spent time over this I had trouble just making a release.

**Comment by paulvi** [comment]
Could you please summaries these changes.
List what is good for users

**Pull request closed without merging**
